-- Store user-provided session notes and reflections in the shared memory table.
-- No session records or claims are generated by this migration.
INSERT INTO memory_category (name, description)
VALUES
    ('spirituality', 'Spiritual practices, beliefs, experiences, and personal reflections'),
    ('medium_sessions', 'Medium session notes, reported messages, dates, and personal interpretations'),
    ('psychic_sessions', 'Psychic session notes, reported readings, dates, and personal reflections')
ON CONFLICT (name) DO NOTHING;
